spring:
  profiles:
    active: local

# 로컬, 개발, 운영 환경의 공통된 설정

  jpa:
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_EMAIL}
    password: ${SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000
    auth-code-expiration-millis: 1800000

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: 1800000

  refresh:
    expiration: 259200000

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_ACCESS_PASSWORD}

springdoc:
  show-login-endpoint: true

server:
  servlet:
    session:
      cookie:
        same-site: none

aes:
  secret:
    key: ${AES_SECRET_KEY}
    salt: ${AES_SECRET_SALT}

location:
  distance: ${STANDARD_DISTANCE}

discord:
  bot:
    token: ${TEST_DISCORD_TOKEN}

  guild:
    id: ${TEST_GUILD_ID}

  channel:
    id: ${TEST_CHANNEL_ID}

profile-image:
  default-folder: ${DEFAULT_PROFILE_IMAGE_FOLDER}
  default-file: ${DEFAULT_PROFILE_IMAGE_FILE}
  default-url: ${DEFAULT_PROFILE_IMAGE_URL}