  # application-test.yml

  spring:
    data:
      redis:
        host: localhost
        port: 6379

    config:
      activate:
        on-profile: test
    datasource:
      url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=MySQL
      username: sa
      password:
      driver-class-name: org.h2.Driver
    h2:
      console:
        enabled: true
    jpa:
      database: h2
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          ddl-auto: create-drop
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect